### ISSUE TITLE
Error using GDAL Virtual File Systems

### ISSUE THREAD

**Issue by lwq-star** [jgomezdans/accra_wkshp#38]
Hi,

I am trying to open and read dem_file using the virtual file systems. when I try to execute **meteo_funcs.py** then it is giving me the following error:
`ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 3: Cannot read 7992978 bytes
ERROR 3: Cannot read 7992978 bytes
ERROR 3: Cannot read 7992978 bytes
ERROR 3: Cannot read 7992978 bytes
ERROR 3: Cannot read 7992978 bytes
ERROR 3: Cannot read 7992978 bytes`
If you can provide some suggestions?

**Comment by jgomezdans** [comment]
Hi,
I'm not sure whether this is running things in Binder or on your own computer, but your problem stems from your GDAL installation not being able to find its projection database. 
Basically, the PROJ_LIB environment variable has to point to the folder where proj.db is installed for your GDAL installation.

**Comment by lwq-star** [comment]
That problem has been solved, but the error 
`ERROR 3: Cannot read 7992978 bytes`
still have.

**Comment by jgomezdans** [comment]
You don't mention whether this is running locally for you, or on Binder or... Can you please give more details?

**Comment by lwq-star** [comment]
Thank you.
This is running locally with win10, Python 3.8.12, and GDAL 3.3.3 . I think I should be able to succeed with a local file.
